### PR TITLE
Installer now takes command line arguments and can run in non-interactive mode.

### PR DESCRIPTION
**Pull request by Ezbob**
Added a simple command line argument parser in the Java source for the Jolie installer tool. 
This allow the Jolie installer script to handle input given to the jar.

As of now only the non-interaction and help option is available but the number of options can be extended by modifying the Jolie installer script `installer.ol`.

### CODE REVIEW

**Comment by fmontesi** [comment]
Cool! Comments:
- I find expressing the logic using `!nonStop` a little weird (you always negate it), how about calling the variable `interactive` (with the opposite boolean logic)?
- Sometimes you do not have spaces inside of round parentheses ( )

@thesave Can you also have a look and help testing?

**Comment by Ezbob** [comment]
@fmontesi Thanks for the feedback.
- `interactive` is probably a better name and it would save some negation operations.
- Do you mean spaces around operators inside parentheses (`(a,b)` vs `(a, b)` ) or spaces after the start or end parentheses ( `(a,b)` vs `( a,b )` ) or both?

**Comment by fmontesi** [comment]
Both :-)

**Comment by Ezbob** [comment]
Hmm... Did some testing by hand and found a bug with the argument parsing in the Java code.. Fixed now. Also I have incorporated the suggestions into the code.

**Comment by thesave** [comment]
I looked at the code, which is ok, and did some tests, all positive :)

**Pull request merged**
